{
 "title": "Demo Dashboard project3",
 "tags": [ "demo" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Time series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.request_status.code_302.count, 10), 20), 'cpu')"
    },
    {
     "target": "alias(statsd.fakesite.counters.session_start.desktop.count, 'memory')"
    }
   ]
  },
  {
   "title": "Gauge1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "scale(apps.backend.backend_01.counters.requests.count, 0.4)"
    }
   ]
  },
  {
   "title": " Gauge2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "scale(apps.backend.backend_01.counters.requests.count, 0.2)"
    }
   ]
  },
  {
   "title": "Time series 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(scaleToSeconds(apps.fakesite.*.counters.requests.count, 1), 2), 2)"
    }
   ]
  },
  {
   "title": "Time series 3",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(summarize(statsd.fakesite.timers.ads_timer.*, '30s', 'avg'), 4)"
    }
   ]
  }
 ]
}